self:
  graphqlUrl: http://trusty-bank:3001/graphql
  hostname: 'trusty-bank'
  mapHostname: 'primary-map'
  openPaymentPublishedPort: 4000
meta: 
  name: 'Trusty Bank'
asset:
  code: USD
  scale: 2
peers:
  - initialLiquidity: '1000000000000'
    peerUrl: http://fynbos:3002
    peerIlpAddress: test.rafiki
accounts:
  - name: 'ACME Commerce'
    path: accounts/acme
    id: 97a3a431-8ee1-48fc-ac85-70e2f5eba8e5
    initialBalance: 1
    postmanEnvVar: pfryPaymentPointer
  - name: 'PlanEx Corp'
    id: a455cc54-b583-455b-836a-e5275c5c05b7
    initialBalance: 2000
    path: accounts/planex
    postmanEnvVar: planexPaymentPointer
fees:
  - fixed: 100
    percentage: 0.02
